### PR TITLE
deleted particle.js file

### PR DESCRIPTION
**Pull request by JASKIRAT11011**
**Describe the Pull Request**

A clear and concise description of what the pull request does.
i have deleted particles.js file from js folder

**Expected Behavior**

**Fixes the Following Issues**

**Screenshots**

image

**Desktop Developed On (please complete the following information):**

- OS: [e.g. Windows]
- Browser [e.g. Edge]
- Browser Version [e.g. 3.9.1]

**Additional Context**

### CODE REVIEW

**Comment by JASKIRAT11011** [comment]
made second PR for hacktober fest

**Comment by JASKIRAT11011** [comment]
made second PR for hacktober fest

**Comment by willtheorangeguy** [comment]
@JASKIRAT11011 Can you also remove the `index.html` file, and then rename the `home.html` file as `index.html`?

**Comment by JASKIRAT11011** [comment]
yes ok doing

**Comment by JASKIRAT11011** [comment]
image
i am not able to see the pull request option , can u please help @willtheorangeguy

**Comment by JASKIRAT11011** [comment]
can you confirm if u recieved the PR?

**Comment by willtheorangeguy** [comment]
Yes I have recieved it, I will approve and merge.

**Review by willtheorangeguy — APPROVED** [review]

**Comment by willtheorangeguy** [comment]
Merged!

**Comment by JASKIRAT11011** [comment]
tysm

**Comment by JASKIRAT11011** [comment]
@willtheorangeguy can u please confirm if this PR is for hacktober fest or not?

**Comment by willtheorangeguy** [comment]
Yes it is, the repository has the `hacktoberfest` tag. I will add the `hacktoberfest-accepted` tag now though.

**Pull request merged**
